% This m-file contains all the GUI elements, such as panels, controls and
% axes. De default values are found in the corresponding uicontrols. The
% m-file is organised according to the sections found in the gui.

% The main gui layout consists of three panels, the top left panel is
% constant and provides section selection. The other two panels actually
% exist 9 times, one for each section. All 9 (times 2) panels are created
% immediately but only one of the 9 is visible, and all other invisible.
% All child objects of the panel automatically switch visibillity state
% allong with their parent. This allows modifications to objects in all 9
% panels, at all times without constant re-rendering of the objects in all
% panels.

% Create GUI figure
% =====================
if headlessmode
    visible = 'off';
else
    visible = 'on';
end

H = figure('units','pixels',...
    'position',[pos.x pos.y pos.w pos.h],...
    'name',['basic gdic (' num2str(bgdicversion,'%3.2f') ')'],...
    'numbertitle','off',...
    'Color',color.bg,...
    'menubar','none',...
    'toolbar','none',...
    'KeyPressFcn',@(H,A)keyPressFcn(H,A),...
    'WindowKeyPressFcn',@(H,A)keyPressFcn(H,A),...
    'WindowScrollWheelFcn',@(H,A)WindowScrollWheelFcn(H,A),...
    'visible',visible,...
    'Tag','BasicGDICuserinterfaces',...
    'resize','on'); drawnow

% Create a uipushtool in the toolbar
CData = ind2rgb(reseticon,gray(255));

gcfpos = get(H,'Position');
pos.w = gcfpos(3);
pos.h = gcfpos(4);

set(H,'HandleVisibility','callback')

% Sections
% =====================

% Visible String
seclabel{1,1} = 'Images';
seclabel{2,1} = 'Pattern Eval.';
seclabel{3,1} = 'ROI and Mask';
seclabel{4,1} = 'Init. Guess';
seclabel{5,1} = 'Basis';
seclabel{6,1} = 'DIC options';
seclabel{7,1} = 'Correlate';
seclabel{8,1} = 'Results';
seclabel{9,1} = 'Info';

% tooltip
secttip{1,1} = 'select images';
secttip{2,1} = 'a priori pattern evaluation';
secttip{3,1} = 'region of interest and masking';
secttip{4,1} = 'initial guess';
secttip{5,1} = 'defining the basis (mesh)';
secttip{6,1} = 'dic options';
secttip{7,1} = 'starting the correlation';
secttip{8,1} = 'post processing';
secttip{9,1} = 'info, status and help';

% Create Panels
% =====================

% panel positions
pos.pan.margin = 10;
pos.pan.width = 250;
pos.pan.width3 = pos.w - (3*pos.pan.margin + pos.pan.width);
pos.pan.height1 = 0.39*(pos.h-3*pos.pan.margin);
pos.pan.height2 = 0.59*(pos.h-3*pos.pan.margin);
pos.pan.height3 = pos.h - (2*pos.pan.margin);
pos.pan.height4 = 0.02*(pos.h-3*pos.pan.margin);
pos.pan1 = [pos.pan.margin 2*pos.pan.margin+pos.pan.height2+pos.pan.height4 pos.pan.width pos.pan.height1];
pos.pan2 = [pos.pan.margin pos.pan.margin pos.pan.width pos.pan.height2];
pos.pan3 = [2*pos.pan.margin+pos.pan.width pos.pan.margin pos.pan.width3 pos.pan.height3];
pos.pan4 = [pos.pan.margin 1.5*pos.pan.margin+pos.pan.height2 pos.pan.width pos.pan.height4];

% panel 1 (Sections)
Hpan1 = uipanel('Title','Sections','FontSize',fontsize(2),...
    'BackgroundColor',color.bg,...
    'TitlePosition','lefttop',...
    'Visible','On',...
    'units','pixels',...
    'Tag','pansections',...
    'Parent',H,...
    'Position',pos.pan1);

% panel 2 (Submenus)
for k = 1:9
    if k == 9
        visible = 'on';
    else
        visible = 'off';
    end
    Hpan2(k) = uipanel('Title',seclabel{k},'FontSize',fontsize(2),...
        'BackgroundColor',color.bg,...
        'TitlePosition','lefttop',...
        'Visible',visible,...
        'units','pixels',...
        'Tag',['secpan' num2str(k)],...
        'Parent',H,...
        'Position',pos.pan2);
end

% panel 3 (Figures)
for k = 1:9
    if k == 9
        visible = 'on';
    else
        visible = 'off';
    end
    Hpan3(k) = uipanel('Title',seclabel{k},'FontSize',fontsize(2),...
        'BackgroundColor',color.bg,...
        'TitlePosition','lefttop',...
        'Visible',visible,...
        'units','pixels',...
        'Tag',['figpan' num2str(k)],...
        'Parent',H,...
        'Position',pos.pan3);
end

% Waitbar
axes('FontSize',fontsize(2),...
    'Color',color.bg,...
    'Box','On',...
    'XTick',[],...
    'YTick',[],...
    'XColor',color.axesfg,...
    'YColor',color.axesfg,...
    'Xlim',[0 1],...
    'Ylim',[0 1],...
    'Visible','On',...
    'units','pixels',...
    'Tag','waitbar',...
    'Parent',H,...
    'Position',pos.pan4);

% Create Section Buttons
% =====================
pos.but.x = 0.2;
pos.but.y = linspace(0.90,0.05,9);
pos.but.width = 0.7;
pos.but.height = 0.08;
for k = 1:9
    if k == 9
        bgcolor = color.hl;
    else
        bgcolor = color.bg;
    end
    % column panel button 1 (Input)
    Hbut(k) = uicontrol('String',seclabel{k},...
        'ToolTipString',secttip{k},...
        'Style','pushbutton',...
        'BackgroundColor',bgcolor,...
        'units','normalized',...
        'Position',[pos.but.x pos.but.y(k) pos.but.width pos.but.height],...
        'FontSize',fontsize(3),...
        'HorizontalAlignment','left',...
        'Tag',['secbut' num2str(k)],...
        'Parent',Hpan1,...
        'call',{@secbutton,H,k});
end

% Create Section Indicators (squares in front)
% =====================
pos.but.indx = 0.07;
pos.but.indwidth = 0.1;
for k = 1:9
    % column panel button 1 (Input)
    Hind(k) = uicontrol('String',num2str(k),...
        'ToolTipString','not ready',...
        'Style','text',...
        'BackgroundColor',color.init,...
        'units','normalized',...
        'Position',[pos.but.indx pos.but.y(k) pos.but.indwidth pos.but.height],...
        'FontSize',fontsize(3),...
        'HorizontalAlignment','center',...
        'Tag',['secind' num2str(k)],...
        'Parent',Hpan1);
    if any(k == [1,3,5,7])
        set(Hind(k),'BackgroundColor',color.off)
    end

end


% ========================================================================
% Section 1: Load images
% ========================================================================
pos.sec1.x1 = 0.05;
pos.sec1.x2 = 0.5;
pos.sec1.y = linspace(0.92,0.02,17);
pos.sec1.w1 = 0.3;
pos.sec1.w2 = 0.2;
pos.sec1.w3 = 0.45;
pos.sec1.w4 = 0.9;
pos.sec1.h1 = 0.048;
pos.sec1.h2 = 0.75;

pos.sec1.x3 = pos.sec1.x1+0.2;
pos.sec1.w5 = 0.18;
pos.sec1.w6 = pos.sec1.w4-0.2;

uicontrol('String','Add files',...
    'ToolTipString','opens a file selection dialogue',...
    'Style','pushbutton',...
    'BackgroundColor',color.bg,...
    'units','normalized',...
    'Position',[pos.sec1.x1 pos.sec1.y(1) pos.sec1.w4 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Tag','fileadd',...
    'Parent',Hpan2(1),...
    'call',{@fileadd,H});

uicontrol('String','Remove files',...
    'ToolTipString','removes selected files',...
    'Style','pushbutton',...
    'BackgroundColor',color.bg,...
    'units','normalized',...
    'Position',[pos.sec1.x1 pos.sec1.y(2) pos.sec1.w4 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Tag','filedel',...
    'Parent',Hpan2(1),...
    'call',{@filedel,H});

uicontrol('String','Up',...
    'ToolTipString','move selected files up',...
    'Style','pushbutton',...
    'BackgroundColor',color.bg,...
    'units','normalized',...
    'Position',[pos.sec1.x1 pos.sec1.y(3) pos.sec1.w3 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Tag','fileup',...
    'Parent',Hpan2(1),...
    'call',{@fileup,H});

uicontrol('String','Down',...
    'ToolTipString','move selected files down',...
    'Style','pushbutton',...
    'BackgroundColor',color.bg,...
    'units','normalized',...
    'Position',[pos.sec1.x2 pos.sec1.y(3) pos.sec1.w3 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Tag','filedown',...
    'Parent',Hpan2(1),...
    'call',{@filedown,H});

uicontrol('String',{''},...
    'Style','listbox',...
    'units','normalized',...
    'BackgroundColor','w',...
    'Position',[pos.sec1.x1 pos.sec1.y(end) pos.sec1.w4 pos.sec1.h2],...
    'FontSize',fontsize(3),...
    'Tag','filelist',...
    'Parent',Hpan2(1),...
    'call',{@fileselect,H});

% Populate figure panel (section 1)
pos.fig.x1 = 0.05;
pos.fig.x2 = 0.14;
pos.fig.x3 = 0.89;
pos.fig.y1 = 0.01;
pos.fig.y2 = 0.1;
pos.fig.w1 = 0.08;
pos.fig.w2 = 0.84;
pos.fig.w4 = 0.9;
pos.fig.h1 = 0.03;
pos.fig.h2 = 0.85;

uicontrol('String','1',...
    'ToolTipString','image id',...
    'Style','edit',...
    'BackgroundColor','w',...
    'units','normalized',...
    'Position',[pos.fig.x1 pos.fig.y1 pos.fig.w1 pos.fig.h1],...
    'FontSize',fontsize(3),...
    'HorizontalAlignment','center',...
    'Tag','imageid',...
    'call',{@imageid,H},...
    'Parent',Hpan3(1));


uicontrol('Style','slider',...
    'BackgroundColor',color.bg,...
    'units','normalized',...
    'Position',[pos.fig.x2 pos.fig.y1 pos.fig.w2 pos.fig.h1],...
    'Tag','imageslider',...
    'Min',1,...
    'Max',2,...
    'Sliderstep',[0.01 0.1],...
    'Value',1,...
    'call',{@imageslider,H},...
    'Parent',Hpan3(1));

axes('Parent',Hpan3(1),...
    'Position',[pos.fig.x1 pos.fig.y2 pos.fig.w4 pos.fig.h2],...
    'Box','On',...
    'NextPlot','Add',...
    'Tag','axes1',...
    'FontSize',fontsize(2));


% ========================================================================
% Section 2: Pattern Eval
% ========================================================================
axes('Parent',Hpan3(2),...
    'Position',[pos.fig.x1 pos.fig.y2 pos.fig.w4 pos.fig.h2],...
    'Box','On',...
    'NextPlot','Add',...
    'Tag','axes2',...
    'FontSize',fontsize(2));

axes('Parent',Hpan2(2),...
    'Position',[pos.sec1.x1+0.05 pos.sec1.y(end)+0.05 pos.sec1.w4-0.05 4*pos.sec1.h1],...
    'Box','On',...
    'NextPlot','Add',...
    'Tag','axes2hist',...
    'FontSize',fontsize(2));

uicontrol('String','1',...
    'ToolTipString','image id',...
    'Style','edit',...
    'BackgroundColor','w',...
    'units','normalized',...
    'Position',[pos.fig.x1 pos.fig.y1 pos.fig.w1 pos.fig.h1],...
    'FontSize',fontsize(3),...
    'HorizontalAlignment','center',...
    'Tag','patid',...
    'call',{@patid,H},...
    'Parent',Hpan3(2));

uicontrol('Style','slider',...
    'BackgroundColor',color.bg,...
    'units','normalized',...
    'Position',[pos.fig.x2 pos.fig.y1 pos.fig.w2 pos.fig.h1],...
    'Tag','patslider',...
    'Min',1,...
    'Max',2,...
    'Sliderstep',[0.01 0.1],...
    'Value',1,...
    'call',{@patslider,H},...
    'Parent',Hpan3(2));

uicontrol('String','Evaluate',...
    'ToolTipString','evaluate the pattern (takes time)',...
    'Style','pushbutton',...
    'BackgroundColor',color.bg,...
    'units','normalized',...
    'Position',[pos.sec1.x1 pos.sec1.y(1) pos.sec1.w4 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Tag','patarea',...
    'Parent',Hpan2(2),...
    'call',{@pateval,H});

uicontrol('String','Show Pattern',...
    'ToolTipString','Show the pattern, with the correlation lenght distribution',...
    'Style','pushbutton',...
    'BackgroundColor',color.hl,...
    'units','normalized',...
    'Position',[pos.sec1.x1 pos.sec1.y(2) pos.sec1.w4 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Tag','patshowpat',...
    'Parent',Hpan2(2),...
    'call',{@patshowpat,H});

uicontrol('String','Show ACF',...
    'ToolTipString','Show the Auto Correlation Function, with the average correlation contour',...
    'Style','pushbutton',...
    'BackgroundColor',color.bg,...
    'units','normalized',...
    'Position',[pos.sec1.x1 pos.sec1.y(3) pos.sec1.w4 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Tag','patshowACF',...
    'Parent',Hpan2(2),...
    'call',{@patshowACF,H});


% ========================================================================
% Section 3: ROI and Mask
% ========================================================================
axes('Parent',Hpan3(3),...
    'Position',[pos.fig.x1 pos.fig.y2 pos.fig.w4 pos.fig.h2],...
    'Box','On',...
    'NextPlot','Add',...
    'Tag','axes3',...
    'FontSize',fontsize(2));

uicontrol('String','1',...
    'ToolTipString','image id',...
    'Style','edit',...
    'BackgroundColor','w',...
    'units','normalized',...
    'Position',[pos.fig.x1 pos.fig.y1 pos.fig.w1 pos.fig.h1],...
    'FontSize',fontsize(3),...
    'HorizontalAlignment','center',...
    'Tag','roiid',...
    'call',{@roiid,H},...
    'Parent',Hpan3(3));

uicontrol('Style','slider',...
    'BackgroundColor',color.bg,...
    'units','normalized',...
    'Position',[pos.fig.x2 pos.fig.y1 pos.fig.w2 pos.fig.h1],...
    'Tag','roislider',...
    'Min',1,...
    'Max',2,...
    'Sliderstep',[0.01 0.1],...
    'Value',1,...
    'call',{@roislider,H},...
    'Parent',Hpan3(3));

uicontrol('String','Set ROI',...
    'ToolTipString','position the region of interest rectangle',...
    'Style','pushbutton',...
    'BackgroundColor',color.bg,...
    'units','normalized',...
    'Position',[pos.sec1.x1 pos.sec1.y(1) pos.sec1.w4 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Tag','roiset',...
    'Parent',Hpan2(3),...
    'call',{@roiset,H});

uicontrol('String','Masking',...
    'Style','text',...
    'FontWeight','bold',...
    'BackgroundColor',color.bg,...
    'units','normalized',...
    'Position',[pos.sec1.x1 pos.sec1.y(3) pos.sec1.w4 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Parent',Hpan2(3));

masktools{1,1} = 'rect';
masktools{2,1} = 'ellipse';
masktools{3,1} = 'polygon';
masktools{4,1} = 'bspline';
masktools{5,1} = 'spot 5px';
masktools{6,1} = 'spot 10px';
masktools{7,1} = 'spot 50px';
uicontrol('String',masktools,...
    'ToolTipString','select a mask shape',...
    'Style','popupmenu',...
    'BackgroundColor','w',...
    'units','normalized',...
    'Position',[pos.sec1.x1 pos.sec1.y(4) pos.sec1.w4 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'HorizontalAlignment','center',...
    'Tag','masktool',...
    'Parent',Hpan2(3));

uicontrol('String','Add',...
    'ToolTipString','select pixels to add to the mask',...
    'Style','pushbutton',...
    'BackgroundColor',color.bg,...
    'units','normalized',...
    'Position',[pos.sec1.x1 pos.sec1.y(5) pos.sec1.w3 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Tag','maskadd',...
    'Parent',Hpan2(3),...
    'call',{@maskset,H,'add'});

uicontrol('String','Del',...
    'ToolTipString','select pixels to delete from the mask',...
    'Style','pushbutton',...
    'BackgroundColor',color.bg,...
    'units','normalized',...
    'Position',[pos.sec1.x2 pos.sec1.y(5) pos.sec1.w3 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Tag','maskdel',...
    'Parent',Hpan2(3),...
    'call',{@maskset,H,'del'});

uicontrol('String','Intersect',...
    'ToolTipString','intersection with selected pixels and the mask',...
    'Style','pushbutton',...
    'BackgroundColor',color.bg,...
    'units','normalized',...
    'Position',[pos.sec1.x1 pos.sec1.y(6) pos.sec1.w3 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Tag','maskintersect',...
    'Parent',Hpan2(3),...
    'call',{@maskset,H,'intersect'});

uicontrol('String','Invert',...
    'ToolTipString','invert the mask',...
    'Style','pushbutton',...
    'BackgroundColor',color.bg,...
    'units','normalized',...
    'Position',[pos.sec1.x2 pos.sec1.y(6) pos.sec1.w3 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Tag','maskinvert',...
    'Parent',Hpan2(3),...
    'call',{@maskinvert,H});

uicontrol('String','Clear',...
    'ToolTipString','clear the entire mask',...
    'Style','pushbutton',...
    'BackgroundColor',color.bg,...
    'units','normalized',...
    'Position',[pos.sec1.x1 pos.sec1.y(7) pos.sec1.w4 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Tag','maskclear',...
    'Parent',Hpan2(3),...
    'call',{@maskclear,H});


uicontrol('String','Save',...
    'ToolTipString','save mask to file',...
    'Style','pushbutton',...
    'BackgroundColor',color.bg,...
    'units','normalized',...
    'Position',[pos.sec1.x1 pos.sec1.y(end) pos.sec1.w3 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Tag','masksave',...
    'Parent',Hpan2(3),...
    'call',{@masksave,H});

uicontrol('String','Load',...
    'ToolTipString','load mask from file',...
    'Style','pushbutton',...
    'BackgroundColor',color.bg,...
    'units','normalized',...
    'Position',[pos.sec1.x2 pos.sec1.y(end) pos.sec1.w3 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Tag','maskload',...
    'Parent',Hpan2(3),...
    'call',{@maskload,H});


% ========================================================================
% Section 4: Init. Guess
% ========================================================================
w = 0.94*pos.fig.w4/2;
h = 0.94*pos.fig.h2/2;
s = 0.08;

% 2014b feature
%     'Clipping','on',...
%     'ClippingStyle','rectangle',...
%     'ClippingStyle','3dbox',...

axes('Parent',Hpan3(4),...
    'Position',[pos.fig.x1 pos.fig.y2+h+s w h],...
    'Box','On',...
    'NextPlot','Add',...
    'Tag','axes41',...
    'FontSize',fontsize(2));
axes('Parent',Hpan3(4),...
    'Position',[pos.fig.x1+w+s pos.fig.y2+h+s w h],...
    'Box','On',...
    'NextPlot','Add',...
    'Tag','axes42',...
    'FontSize',fontsize(2));
axes('Parent',Hpan3(4),...
    'Position',[pos.fig.x1 pos.fig.y2 w h],...
    'Box','On',...
    'NextPlot','Add',...
    'Tag','axes43',...
    'FontSize',fontsize(2));
axes('Parent',Hpan3(4),...
    'Position',[pos.fig.x1+w+s pos.fig.y2 w h],...
    'Box','On',...
    'NextPlot','Add',...
    'Tag','axes44',...
    'FontSize',fontsize(2));

uicontrol('String','1',...
    'ToolTipString','image id',...
    'Style','edit',...
    'BackgroundColor','w',...
    'units','normalized',...
    'Position',[pos.fig.x1 pos.fig.y1 pos.fig.w1 pos.fig.h1],...
    'FontSize',fontsize(3),...
    'HorizontalAlignment','center',...
    'Tag','iguessid',...
    'call',{@iguessid,H},...
    'Parent',Hpan3(4));

uicontrol('Style','slider',...
    'BackgroundColor',color.bg,...
    'units','normalized',...
    'Position',[pos.fig.x2 pos.fig.y1 pos.fig.w2 pos.fig.h1],...
    'Tag','iguessslider',...
    'Min',1,...
    'Max',2,...
    'Sliderstep',[0.01 0.1],...
    'Value',1,...
    'call',{@iguessslider,H},...
    'Parent',Hpan3(4));

% 5. Image processing
uicontrol('String','Image Processing',...
    'ToolTipString','create processed images',...
    'Style','pushbutton',...
    'BackgroundColor',color.bg,...
    'units','normalized',...
    'Position',[pos.sec1.x1 pos.sec1.y(1) pos.sec1.w4 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Tag','iguessimprocess',...
    'Parent',Hpan2(4),...
    'call',{@iguessimprocess,H});

uicontrol('String','Blur',...
    'Style','text',...
    'BackgroundColor',color.bg,...
    'HorizontalAlignment','left',...
    'units','normalized',...
    'Position',[pos.sec1.x1 pos.sec1.y(2) pos.sec1.w3 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Parent',Hpan2(4));
uicontrol('String',ini.iguessblur.value,...
    'ToolTipString','gaussian blur radius [px]',...
    'Style','edit',...
    'BackgroundColor','w',...
    'units','normalized',...
    'Position',[pos.sec1.x2 pos.sec1.y(2) pos.sec1.w3 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Tag','iguessblur',...
    'Parent',Hpan2(4));

uicontrol('String','Im. process',...
    'Style','text',...
    'BackgroundColor',color.bg,...
    'HorizontalAlignment','left',...
    'units','normalized',...
    'Position',[pos.sec1.x1 pos.sec1.y(3) pos.sec1.w3 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Parent',Hpan2(4));
improcesstype{1,1} = 'none';
improcesstype{2,1} = 'grad|xy|';
improcesstype{3,1} = 'grad|x|';
improcesstype{4,1} = 'grad|y|';
improcesstype{5,1} = 'grad(xy)';
improcesstype{6,1} = 'grad(x)';
improcesstype{7,1} = 'grad(y)';
uicontrol('String',improcesstype,...
    'ToolTipString','process the image',...
    'Style','popupmenu',...
    'Value',ini.iguessimprocesstype.value,...
    'BackgroundColor','w',...
    'units','normalized',...
    'Position',[pos.sec1.x2 pos.sec1.y(3) pos.sec1.w3 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Tag','iguessimprocesstype',...
    'Parent',Hpan2(4));

% 5. Auto Iguess
uicontrol('String','Add auto',...
    'ToolTipString','apply a local (FFT) algorithm to obtain the initial guess',...
    'Style','pushbutton',...
    'BackgroundColor',color.bg,...
    'units','normalized',...
    'Position',[pos.sec1.x1 pos.sec1.y(6) pos.sec1.w4 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Tag','iguessaddauto',...
    'Parent',Hpan2(4),...
    'call',{@iguessaddauto,H});


% 5. Manual Iguess
uicontrol('String','Add manual',...
    'ToolTipString','add a initial guess point manually',...
    'Style','pushbutton',...
    'BackgroundColor',color.bg,...
    'units','normalized',...
    'Position',[pos.sec1.x1 pos.sec1.y(7) pos.sec1.w4 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Tag','iguessaddmanual',...
    'Parent',Hpan2(4),...
    'call',{@iguessaddmanual,H});

uicontrol('String','zoomselect',...
    'Style','checkbox',...
    'Value',ini.iguesszoomselect.value,...
    'BackgroundColor',color.bg,...
    'HorizontalAlignment','left',...
    'units','normalized',...
    'Position',[pos.sec1.x1 pos.sec1.y(8) pos.sec1.w3 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Tag','iguesszoomselect',...
    'Parent',Hpan2(4));
uicontrol('String',ini.iguesszoomsize.value,...
    'ToolTipString','zone of interest (subset) size',...
    'Style','edit',...
    'BackgroundColor','w',...
    'units','normalized',...
    'Position',[pos.sec1.x2 pos.sec1.y(8) pos.sec1.w3 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Tag','iguesszoomsize',...
    'Parent',Hpan2(4));

% Delete
uicontrol('String','Delete',...
    'Style','text',...
    'FontWeight','bold',...
    'BackgroundColor',color.bg,...
    'units','normalized',...
    'Position',[pos.sec1.x1 pos.sec1.y(10) pos.sec1.w4 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Parent',Hpan2(4));

pos.sec1.wb = (pos.sec1.w4/3) - 0.01;
pos.sec1.xb(1) = pos.sec1.x1;
pos.sec1.xb(2) = pos.sec1.x1 + 1*pos.sec1.wb + 1*0.01;
pos.sec1.xb(3) = pos.sec1.x1 + 2*pos.sec1.wb + 2*0.01;

uicontrol('String','One',...
    'ToolTipString','select one point to delete',...
    'Style','pushbutton',...
    'BackgroundColor',color.bg,...
    'units','normalized',...
    'Position',[pos.sec1.xb(1) pos.sec1.y(11) pos.sec1.wb pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Tag','iguessdelone',...
    'Parent',Hpan2(4),...
    'call',{@iguessdelone,H});

uicontrol('String','Area',...
    'ToolTipString','clear the initial guess in an area',...
    'Style','pushbutton',...
    'BackgroundColor',color.bg,...
    'units','normalized',...
    'Position',[pos.sec1.xb(2) pos.sec1.y(11) pos.sec1.wb pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Tag','iguessdelbox',...
    'Parent',Hpan2(4),...
    'call',{@iguessdelbox,H});

uicontrol('String','All',...
    'ToolTipString','clear the initial guess',...
    'Style','pushbutton',...
    'BackgroundColor',color.bg,...
    'units','normalized',...
    'Position',[pos.sec1.xb(3) pos.sec1.y(11) pos.sec1.wb pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Tag','iguessdelall',...
    'Parent',Hpan2(4),...
    'call',{@iguessdelall,H});

% This Frame
uicontrol('String','Single frame operations',...
    'Style','text',...
    'FontWeight','bold',...
    'BackgroundColor',color.bg,...
    'units','normalized',...
    'Position',[pos.sec1.x1 pos.sec1.y(13) pos.sec1.w4 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Parent',Hpan2(4));

uicontrol('String','Zero',...
    'ToolTipString','Set all initial guess points to zero for this frame',...
    'Style','pushbutton',...
    'BackgroundColor',color.bg,...
    'units','normalized',...
    'Position',[pos.sec1.xb(1) pos.sec1.y(14) pos.sec1.wb pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Tag','iguessdelone',...
    'Parent',Hpan2(4),...
    'call',{@iguessframezero,H});

uicontrol('String','Auto',...
    'ToolTipString','Perform the auto initial guess for this frame only',...
    'Style','pushbutton',...
    'BackgroundColor',color.bg,...
    'units','normalized',...
    'Position',[pos.sec1.xb(2) pos.sec1.y(14) pos.sec1.wb pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Tag','iguessdelbox',...
    'Parent',Hpan2(4),...
    'call',{@iguessframeauto,H});

uicontrol('String','Interpolate',...
    'ToolTipString','interpolate (in time) the displacements of each iguess point in this frame based on the other frames',...
    'Style','pushbutton',...
    'BackgroundColor',color.bg,...
    'units','normalized',...
    'Position',[pos.sec1.xb(3) pos.sec1.y(14) pos.sec1.wb pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Tag','iguessdelall',...
    'Parent',Hpan2(4),...
    'call',{@iguessframeint,H});

uicontrol('String','Save',...
    'ToolTipString','save initial guess to file',...
    'Style','pushbutton',...
    'BackgroundColor',color.bg,...
    'units','normalized',...
    'Position',[pos.sec1.x1 pos.sec1.y(end) pos.sec1.w3 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Tag','iguesssave',...
    'Parent',Hpan2(4),...
    'call',{@iguesssave,H});

uicontrol('String','Load',...
    'ToolTipString','load initialguess from file',...
    'Style','pushbutton',...
    'BackgroundColor',color.bg,...
    'units','normalized',...
    'Position',[pos.sec1.x2 pos.sec1.y(end) pos.sec1.w3 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Tag','iguessload',...
    'Parent',Hpan2(4),...
    'call',{@iguessload,H});

% ========================================================================
% Section 5: Basis
% ========================================================================
uicontrol('String','1',...
    'ToolTipString','basis function id',...
    'Style','edit',...
    'BackgroundColor','w',...
    'units','normalized',...
    'Position',[pos.fig.x1 pos.fig.y1 pos.fig.w1 pos.fig.h1],...
    'FontSize',fontsize(3),...
    'HorizontalAlignment','center',...
    'Tag','phiid',...
    'call',{@phiid,H},...
    'Parent',Hpan3(5));

uicontrol('Style','slider',...
    'BackgroundColor',color.bg,...
    'units','normalized',...
    'Position',[pos.fig.x2 pos.fig.y1 pos.fig.w2 pos.fig.h1],...
    'Tag','phislider',...
    'Min',1,...
    'Max',2,...
    'Sliderstep',[0.01 0.1],...
    'Value',1,...
    'call',{@phislider,H},...
    'Parent',Hpan3(5));

axes('Parent',Hpan3(5),...
    'Position',[pos.fig.x1 pos.fig.y2 pos.fig.w4 pos.fig.h2],...
    'Box','On',...
    'NextPlot','Add',...
    'Tag','axes4',...
    'FontSize',fontsize(2));

% Basis Selector
% ===================
uicontrol('String',{'basis 1';'basis 2';'basis 3';'basis 4'},...
    'ToolTipString','select the basis to show or (re)define',...
    'Value',1,...
    'Style','listbox',...
    'BackgroundColor','w',...
    'units','normalized',...
    'Position',[pos.sec1.x1 pos.sec1.y(4) pos.sec1.w4 4.5*pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Tag','basislist',...
    'call',{@basislist,H},...
    'Parent',Hpan2(5));

uicontrol('String','New',...
    'ToolTipString','add a new basis',...
    'Style','pushbutton',...
    'BackgroundColor',color.bg,...
    'units','normalized',...
    'Position',[pos.sec1.xb(1) pos.sec1.y(5) pos.sec1.wb pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Tag','basisnew',...
    'Parent',Hpan2(5),...
    'call',{@basisnew,H});
uicontrol('String','Del',...
    'ToolTipString','delete this basis',...
    'Style','pushbutton',...
    'BackgroundColor',color.bg,...
    'units','normalized',...
    'Position',[pos.sec1.xb(2) pos.sec1.y(5) pos.sec1.wb pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Tag','basisdel',...
    'Parent',Hpan2(5),...
    'call',{@basisdel,H});
uicontrol('String','Dupl.',...
    'ToolTipString','duplicate this bases',...
    'Style','pushbutton',...
    'BackgroundColor',color.bg,...
    'units','normalized',...
    'Position',[pos.sec1.xb(3) pos.sec1.y(5) pos.sec1.wb pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Tag','basisduplicate',...
    'Parent',Hpan2(5),...
    'call',{@basisduplicate,H});

basistypes{1,1} = 'Polynomial';
basistypes{2,1} = 'Harmonic';
basistypes{3,1} = 'Zernike';
basistypes{4,1} = 'B-Spline';
basistypes{5,1} = 'FEM Triangle (a)';
basistypes{6,1} = 'FEM Triangle (b)';
basistypes{7,1} = 'FEM Quad';
uicontrol('String',basistypes,...
    'ToolTipString','basis type (shape function family)',...
    'Value',ini.basistype.value,...
    'Style','popupmenu',...
    'BackgroundColor','w',...
    'units','normalized',...
    'Position',[pos.sec1.x1 pos.sec1.y(7) pos.sec1.w4 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Tag','basistype',...
    'call',{@basistype,H},...
    'Parent',Hpan2(5));

uicontrol('String','Basis name',...
    'Style','text',...
    'BackgroundColor',color.bg,...
    'HorizontalAlignment','left',...
    'units','normalized',...
    'Position',[pos.sec1.x1 pos.sec1.y(8) pos.sec1.w3 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Parent',Hpan2(5));
uicontrol('String','basis 1',...
    'ToolTipString','descriptive name for this basis set',...
    'Style','edit',...
    'Enable','On',...
    'BackgroundColor','w',...
    'units','normalized',...
    'Position',[pos.sec1.x2 pos.sec1.y(8) pos.sec1.w3 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Tag','basisname',...
    'Parent',Hpan2(5));

uicontrol('String','Boundary ratio',...
    'Style','text',...
    'BackgroundColor',color.bg,...
    'HorizontalAlignment','left',...
    'units','normalized',...
    'Position',[pos.sec1.x1 pos.sec1.y(9) pos.sec1.w3 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Parent',Hpan2(5));
uicontrol('String',ini.basisboundary.value,...
    'ToolTipString','size ratio of boundary elements with respect to internal elements',...
    'Style','edit',...
    'Enable','Off',...
    'BackgroundColor','w',...
    'units','normalized',...
    'Position',[pos.sec1.x2 pos.sec1.y(9) pos.sec1.w3 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Tag','basisboundary',...
    'Parent',Hpan2(5));

uicontrol('String','Rows',...
    'Style','text',...
    'BackgroundColor',color.bg,...
    'HorizontalAlignment','left',...
    'units','normalized',...
    'Position',[pos.sec1.x1 pos.sec1.y(10) pos.sec1.w3 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Parent',Hpan2(5));
uicontrol('String',ini.basisrows.value,...
    'ToolTipString','number of "nodes/knots" along the x-direction',...
    'Style','edit',...
    'Enable','off',...
    'BackgroundColor','w',...
    'units','normalized',...
    'Position',[pos.sec1.x2 pos.sec1.y(10) pos.sec1.w3 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Tag','basisrows',...
    'Parent',Hpan2(5));

uicontrol('String','Cols',...
    'Style','text',...
    'BackgroundColor',color.bg,...
    'HorizontalAlignment','left',...
    'units','normalized',...
    'Position',[pos.sec1.x1 pos.sec1.y(11) pos.sec1.w3 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Parent',Hpan2(5));
uicontrol('String',ini.basiscols.value,...
    'ToolTipString','number of "nodes/knots" along the y-direction',...
    'Style','edit',...
    'Enable','off',...
    'BackgroundColor','w',...
    'units','normalized',...
    'Position',[pos.sec1.x2 pos.sec1.y(11) pos.sec1.w3 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Tag','basiscols',...
    'Parent',Hpan2(5));

uicontrol('String','Order',...
    'Style','text',...
    'BackgroundColor',color.bg,...
    'HorizontalAlignment','left',...
    'units','normalized',...
    'Position',[pos.sec1.x1 pos.sec1.y(12) pos.sec1.w3 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Parent',Hpan2(5));
uicontrol('String',ini.basisorder.value,...
    'ToolTipString','polynomial order',...
    'Style','edit',...
    'Enable','On',...
    'BackgroundColor','w',...
    'units','normalized',...
    'Position',[pos.sec1.x2 pos.sec1.y(12) pos.sec1.w3 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Tag','basisorder',...
    'Parent',Hpan2(5));

uicontrol('String','Define Basis',...
    'ToolTipString','Generate the basis',...
    'Style','pushbutton',...
    'BackgroundColor',color.bg,...
    'units','normalized',...
    'Position',[pos.sec1.x1 pos.sec1.y(13) pos.sec1.w4 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'call',{@basisbuild,H},...
    'Tag','basisdefine',...
    'Parent',Hpan2(5));

% =================

uicontrol('String',ini.basissoften.value,...
    'Style','edit',...
    'Enable','inactive',...
    'BackgroundColor',color.bg,...
    'HorizontalAlignment','center',...
    'units','normalized',...
    'Position',[pos.sec1.x1 pos.sec1.y(end-2) pos.sec1.w5 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Tag','basissoften',...
    'Parent',Hpan2(5));
uicontrol('Style','slider',...
    'ToolTipString','soften the pattern',...
    'BackgroundColor',color.bg,...
    'units','normalized',...
    'Position',[pos.sec1.x3 pos.sec1.y(end-2) pos.sec1.w6 pos.sec1.h1],...
    'Tag','basissoftenslider',...
    'Min',0,...
    'Max',1,...
    'Sliderstep',[0.01 0.1],...
    'Value',str2double(ini.basissoften.value),...
    'call',{@plotbasis,H},...
    'Parent',Hpan2(5));

uicontrol('String',ini.basisalpha.value,...
    'Style','edit',...
    'Enable','inactive',...
    'BackgroundColor',color.bg,...
    'HorizontalAlignment','center',...
    'units','normalized',...
    'Position',[pos.sec1.x1 pos.sec1.y(end-1) pos.sec1.w5 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Tag','basisalpha',...
    'Parent',Hpan2(5));
uicontrol('Style','slider',...
    'ToolTipString','overlay transparancy',...
    'BackgroundColor',color.bg,...
    'units','normalized',...
    'Position',[pos.sec1.x3 pos.sec1.y(end-1) pos.sec1.w6 pos.sec1.h1],...
    'Tag','basisalphaslider',...
    'Min',0,...
    'Max',1,...
    'Sliderstep',[0.01 0.1],...
    'Value',str2double(ini.basisalpha.value),...
    'call',{@plotbasis,H},...
    'Parent',Hpan2(5));


% Save / Load
uicontrol('String','Save',...
    'ToolTipString','save basis to file',...
    'Style','pushbutton',...
    'BackgroundColor',color.bg,...
    'units','normalized',...
    'Position',[pos.sec1.x1 pos.sec1.y(end) pos.sec1.w3 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Tag','basissave',...
    'Parent',Hpan2(5),...
    'call',{@basissave,H});

uicontrol('String','Load',...
    'ToolTipString','load basis from file',...
    'Style','pushbutton',...
    'BackgroundColor',color.bg,...
    'units','normalized',...
    'Position',[pos.sec1.x2 pos.sec1.y(end) pos.sec1.w3 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Tag','basisload',...
    'Parent',Hpan2(5),...
    'call',{@basisload,H});


% ========================================================================
% Section 6: DIC Options
% ========================================================================
w7 = 0.15;
 

uicontrol('String','Dimen.',...
    'Style','text',...
    'BackgroundColor',color.bg,...
    'HorizontalAlignment','left',...
    'units','normalized',...
    'Position',[pos.sec1.x1 pos.sec1.y(1) pos.sec1.w3-w7 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Parent',Hpan2(6));
dimensions{1,1} = '2D';
dimensions{2,1} = 'Quasi 3D';
uicontrol('String',dimensions,...
    'ToolTipString','2D analysis or 3D surface analysis',...
    'Style','popupmenu',...
    'Value',ini.dicdimensions.value,...
    'BackgroundColor','w',...
    'units','normalized',...
    'Position',[pos.sec1.x2-w7 pos.sec1.y(1) pos.sec1.w3+w7 pos.sec1.h1],...
    'FontSize',fontsize(2),...
    'Tag','dicdimensions',...
    'Parent',Hpan2(6),...
    'call',{@dicdimensions,H});

uicontrol('String','Relax.',...
    'Style','text',...
    'BackgroundColor',color.bg,...
    'HorizontalAlignment','left',...
    'units','normalized',...
    'Position',[pos.sec1.x1 pos.sec1.y(2) pos.sec1.w3-w7 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Parent',Hpan2(6));
uicontrol('String',{'none','constant','linear','quadratic','cubic'},...
    'ToolTipString','relax the brightness conservation equation, each level adds a field to be solved (deal with grayvalue intensity changes)',...
    'Style','popupmenu',...
    'Value',ini.dicrelaxation.value,...
    'Enable','on',...
    'BackgroundColor','w',...
    'units','normalized',...
    'Position',[pos.sec1.x2-w7 pos.sec1.y(2) pos.sec1.w3+w7 pos.sec1.h1],...
    'FontSize',fontsize(2),...
    'Tag','dicrelaxation',...
    'Parent',Hpan2(6),...
    'call',{@dicrelaxation,H});

dicrelbasis = {'same as U';'basis 1';'basis 2';'basis 3';'basis 4'};
uicontrol('String','Rel. Basis',...
    'Style','text',...
    'BackgroundColor',color.bg,...
    'HorizontalAlignment','left',...
    'units','normalized',...
    'Position',[pos.sec1.x1 pos.sec1.y(3) pos.sec1.w3-w7 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Parent',Hpan2(6));
uicontrol('String',dicrelbasis,...
    'ToolTipString','Choose a basis to use for the relaxed brightness (and contrast) fields',...
    'Style','popupmenu',...
    'Value',min([5 ini.dicrelbasis.value]),...
    'Enable','on',...
    'BackgroundColor','w',...
    'units','normalized',...
    'enable','off',...
    'Position',[pos.sec1.x2-w7 pos.sec1.y(3) pos.sec1.w3+w7 pos.sec1.h1],...
    'FontSize',fontsize(2),...
    'Tag','dicrelbasis',...
    'Parent',Hpan2(6));


uicontrol('String','Conv. Cr.',...
    'Style','text',...
    'BackgroundColor',color.bg,...
    'HorizontalAlignment','left',...
    'units','normalized',...
    'Position',[pos.sec1.x1 pos.sec1.y(4) pos.sec1.w3-w7 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Parent',Hpan2(6));
dicconvparam{1,1} = 'change in disp.';
dicconvparam{2,1} = 'right hand member';
dicconvparam{3,1} = 'update in dof';
dicconvparam{4,1} = 'change in residual';
uicontrol('String',dicconvparam,...
    'ToolTipString','convergence parameter',...
    'Style','popupmenu',...
    'Value',ini.dicconvparam.value,...
    'BackgroundColor','w',...
    'units','normalized',...
    'Position',[pos.sec1.x2-w7 pos.sec1.y(4) pos.sec1.w3+w7 pos.sec1.h1],...
    'FontSize',fontsize(2),...
    'Tag','dicconvparam',...
    'Parent',Hpan2(6));

uicontrol('String','Best iter.',...
    'Style','text',...
    'BackgroundColor',color.bg,...
    'HorizontalAlignment','left',...
    'units','normalized',...
    'Position',[pos.sec1.x1 pos.sec1.y(5) pos.sec1.w3-w7 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Parent',Hpan2(6));
bestitparam{1,1} = 'residual';
bestitparam{2,1} = 'change in disp.';
bestitparam{3,1} = 'right hand member';
bestitparam{4,1} = 'update in dof';
bestitparam{5,1} = 'change in residual';
bestitparam{6,1} = 'last it.';
uicontrol('String',bestitparam,...
    'ToolTipString','Use the best known iteration instead of the last (based on:)',...
    'Style','popupmenu',...
    'Value',ini.dicbestit.value,...
    'BackgroundColor','w',...
    'units','normalized',...
    'Position',[pos.sec1.x2-w7 pos.sec1.y(5) pos.sec1.w3+w7 pos.sec1.h1],...
    'FontSize',fontsize(2),...
    'Tag','dicbestit',...
    'Parent',Hpan2(6));

uicontrol('String','Max div.',...
    'Style','text',...
    'BackgroundColor',color.bg,...
    'HorizontalAlignment','left',...
    'units','normalized',...
    'Position',[pos.sec1.x1 pos.sec1.y(6) pos.sec1.w3-w7 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Parent',Hpan2(6));
uicontrol('String',ini.dicmaxdiv.value,...
    'ToolTipString','stop after N diverging steps (based on the residual)',...
    'Style','edit',...
    'BackgroundColor','w',...
    'units','normalized',...
    'Position',[pos.sec1.x2-w7 pos.sec1.y(6) pos.sec1.w3+w7 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Tag','dicmaxdiv',...
    'Parent',Hpan2(6));

% incremental initial guess
uicontrol('String','Init.',...
    'Style','text',...
    'Value',1,...
    'BackgroundColor',color.bg,...
    'HorizontalAlignment','left',...
    'units','normalized',...
    'Position',[pos.sec1.x1 pos.sec1.y(7) pos.sec1.w3-w7 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Parent',Hpan2(6));
inciguess{1,1} = 'zero';
inciguess{2,1} = 'init. guess';
inciguess{3,1} = 'prev. inc.';
inciguess{4,1} = 'prev. inc. and init. guess';
inciguess{5,1} = 'reuse';
uicontrol('String',inciguess,...
    'ToolTipString','what to use for initial guess for the next increment',...
    'Style','popupmenu',...
    'Value',ini.dicinciguess.value,...
    'BackgroundColor','w',...
    'units','normalized',...
    'Position',[pos.sec1.x2-w7 pos.sec1.y(7) pos.sec1.w3+w7 pos.sec1.h1],...
    'FontSize',fontsize(2),...
    'Tag','dicinciguess',...
    'Parent',Hpan2(6));


uicontrol('String','Total',...
    'ToolTipString','the "Total Lagrange" method compares each image to the first image',...
    'Style','text',...
    'BackgroundColor',color.bg,...
    'HorizontalAlignment','left',...
    'units','normalized',...
    'Position',[pos.sec1.x1+0.2 pos.sec1.y(9) pos.sec1.w3-0.1 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Parent',Hpan2(6));
uicontrol('String','Updated',...
    'ToolTipString','the "Updated Lagrange" method compares each image to back-deformed version of the previous image',...
    'Style','text',...
    'BackgroundColor',color.bg,...
    'HorizontalAlignment','right',...
    'units','normalized',...
    'Position',[pos.sec1.x2+0.1 pos.sec1.y(9) pos.sec1.w3-0.1 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Parent',Hpan2(6));
uicontrol('String',ini.diclagrange.value,...
    'Style','edit',...
    'Enable','inactive',...
    'BackgroundColor',color.bg,...
    'HorizontalAlignment','center',...
    'units','normalized',...
    'Position',[pos.sec1.x1 pos.sec1.y(10) 0.18 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Tag','diclagrange',...
    'Parent',Hpan2(6));
uicontrol('Style','slider',...
    'ToolTipString','Shift between the "Total Lagrange" (accurate) or the "Updated Lagrange" (robust) method',...
    'BackgroundColor',color.bg,...
    'units','normalized',...
    'Position',[pos.sec1.x1+0.2 pos.sec1.y(10) pos.sec1.w4-0.2 pos.sec1.h1],...
    'Tag','diclagrangeslider',...
    'Min',0,...
    'Max',1,...
    'Sliderstep',[0.01 0.1],...
    'Value',str2double(ini.diclagrange.value),...
    'call',{@diclagrangeslider,H},...
    'Parent',Hpan2(6));

uicontrol('String','Auto save',...
    'Style','text',...
    'BackgroundColor',color.bg,...
    'HorizontalAlignment','left',...
    'units','normalized',...
    'Position',[pos.sec1.x1 pos.sec1.y(end-4) pos.sec1.w3 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Parent',Hpan2(6));
uicontrol('String',{'0';'1'},...
    'ToolTipString','save the correlation results after each increment',...
    'Style','popupmenu',...
    'Value',ini.dicautosave.value,...
    'BackgroundColor','w',...
    'units','normalized',...
    'Position',[pos.sec1.x2 pos.sec1.y(end-4) pos.sec1.w3 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Tag','dicautosave',...
    'Parent',Hpan2(6));

uicontrol('String','Mem. save',...
    'Style','text',...
    'BackgroundColor',color.bg,...
    'HorizontalAlignment','left',...
    'units','normalized',...
    'Position',[pos.sec1.x1 pos.sec1.y(end-3) pos.sec1.w3 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Parent',Hpan2(6));
uicontrol('String',{'0';'1';'2'},...
    'ToolTipString','reduce memory requirement, (0 = full L matrix in memory, 1 = L matrix per dimension, 2 = L matrix per dof)',...
    'Style','popupmenu',...
    'Value',ini.dicmemsave.value,...
    'BackgroundColor','w',...
    'units','normalized',...
    'Position',[pos.sec1.x2 pos.sec1.y(end-3) pos.sec1.w3 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Tag','dicmemsave',...
    'Parent',Hpan2(6));

uicontrol('String','Precision',...
    'Style','text',...
    'BackgroundColor',color.bg,...
    'HorizontalAlignment','left',...
    'units','normalized',...
    'Position',[pos.sec1.x1 pos.sec1.y(end-2) pos.sec1.w3 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Parent',Hpan2(6));
uicontrol('String',{'single';'double'},...
    'ToolTipString','use single (32 bit) or double (64 bit) precision floating point matrices (single disables sparse matrices)',...
    'Style','popupmenu',...
    'Value',ini.dicprecision.value,...
    'BackgroundColor','w',...
    'units','normalized',...
    'Position',[pos.sec1.x2 pos.sec1.y(end-2) pos.sec1.w3 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Tag','dicprecision',...
    'Parent',Hpan2(6));

uicontrol('String','use GPU',...
    'Style','text',...
    'BackgroundColor',color.bg,...
    'HorizontalAlignment','left',...
    'units','normalized',...
    'Position',[pos.sec1.x1 pos.sec1.y(end-1) pos.sec1.w3 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Parent',Hpan2(6));
uicontrol('String',{'0';'1'},...
    'ToolTipString','Use the Graphics card for the correlation computations (requires CUDA capable GPU, see help gpuDevice)',...
    'Style','popupmenu',...
    'Value',ini.dicusegpu.value,...
    'BackgroundColor','w',...
    'units','normalized',...
    'Position',[pos.sec1.x2 pos.sec1.y(end-1) pos.sec1.w3 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Tag','dicusegpu',...
    'Parent',Hpan2(6));

uicontrol('String','Save',...
    'ToolTipString','save dic options to file',...
    'Style','pushbutton',...
    'BackgroundColor',color.bg,...
    'units','normalized',...
    'Position',[pos.sec1.x1 pos.sec1.y(end) pos.sec1.w3 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Tag','dicsave',...
    'Parent',Hpan2(6),...
    'call',{@dicsave,H});

uicontrol('String','Load',...
    'ToolTipString','load dic options from file',...
    'Style','pushbutton',...
    'BackgroundColor',color.bg,...
    'units','normalized',...
    'Position',[pos.sec1.x2 pos.sec1.y(end) pos.sec1.w3 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Tag','dicload',...
    'Parent',Hpan2(6),...
    'call',{@dicload,H});


cgtypes{1,1} = 'Preparation';
cgtypes{2,1} = 'Preparation';
cgtypes{3,1} = 'Preparation';
cgtypes{4,1} = 'Final';

cgstr{1,1} = 'prepA';
cgstr{2,1} = 'prepB';
cgstr{3,1} = 'prepC';
cgstr{4,1} = 'final';

pos.cgx = linspace(10,pos.pan3(3)-10,5);
pos.cgy = 10;
pos.cgh = min([451 pos.pan3(4)]);
pos.cgw = diff(pos.cgx(1:2))-5;

pos.cg(1,:) = [pos.cgx(1) pos.cgy pos.cgw pos.cgh];
pos.cg(2,:) = [pos.cgx(2) pos.cgy pos.cgw pos.cgh];
pos.cg(3,:) = [pos.cgx(3) pos.cgy pos.cgw pos.cgh];
pos.cg(4,:) = [pos.cgx(4) pos.cgy pos.cgw pos.cgh];

dicgradient{1,1} = 'auto';
dicgradient{2,1} = 'gradfg';
dicgradient{3,1} = 'gradf';
dicgradient{4,1} = 'gradg';


% ========================================================================
for k = 1:4
    % Create CG settings panels
    % =====================
    Hcgpan(k) = uipanel('Title',cgtypes{k},'FontSize',fontsize(2),...
        'BackgroundColor',color.bg,...
        'TitlePosition','centertop',...
        'Visible','on',...
        'units','pixels',...
        'Tag',['cgpan' num2str(k)],...
        'Parent',Hpan3(6),...
        'Position',pos.cg(k,:));
    
    if k <= 3
        % Enabled?
        if ini.([cgstr{k} 'on']).value == 1
            cgAon = true;
            cgAoff = false;
            enabled = 'on';
        else
            cgAon = false;
            cgAoff = true;
            enabled = 'off';
        end
        
        % Create CG controls
        % =====================
        uicontrol('String','On',...
            'ToolTipString','switch current coarse grain step on',...
            'Style','togglebutton',...
            'Value',cgAon,...
            'BackgroundColor',color.hl,...
            'units','normalized',...
            'Position',[pos.sec1.x1 pos.sec1.y(1) pos.sec1.w3 1.5*pos.sec1.h1],...
            'FontSize',fontsize(3),...
            'Tag',[cgstr{k} 'on'],...
            'Parent',Hcgpan(k),...
            'call',{@cgon,H,k});
        
        uicontrol('String','Off',...
            'ToolTipString','switch current coarse grain step off',...
            'Style','togglebutton',...
            'Value',cgAoff,...
            'BackgroundColor',color.bg,...
            'units','normalized',...
            'Position',[pos.sec1.x2 pos.sec1.y(1) pos.sec1.w3 1.5*pos.sec1.h1],...
            'FontSize',fontsize(3),...
            'Tag',[cgstr{k} 'off'],...
            'Parent',Hcgpan(k),...
            'call',{@cgoff,H,k});
    end
    
    uicontrol('String','Blur',...
        'Style','text',...
        'BackgroundColor',color.bg,...
        'HorizontalAlignment','left',...
        'units','normalized',...
        'Position',[pos.sec1.x1 pos.sec1.y(3) pos.sec1.w3 pos.sec1.h1],...
        'FontSize',fontsize(3),...
        'Parent',Hcgpan(k));
    uicontrol('String',ini.([cgstr{k} 'blur']).value,...
        'ToolTipString','gaussian blur radius [px]',...
        'Style','edit',...
        'BackgroundColor','w',...
        'Units','normalized',...
        'Enable',enabled,...
        'Position',[pos.sec1.x2 pos.sec1.y(3) pos.sec1.w3 pos.sec1.h1],...
        'FontSize',fontsize(3),...
        'Tag',[cgstr{k} 'blur'],...
        'Parent',Hcgpan(k));
    
    uicontrol('String','Coarsegrain',...
        'Style','text',...
        'BackgroundColor',color.bg,...
        'HorizontalAlignment','left',...
        'units','normalized',...
        'Position',[pos.sec1.x1 pos.sec1.y(4) pos.sec1.w3 pos.sec1.h1],...
        'FontSize',fontsize(3),...
        'Parent',Hcgpan(k));
    uicontrol('String',ini.([cgstr{k} 'level']).value,...
        'ToolTipString','coarse grain N times (i.e. superpixel size 2^N)',...
        'Style','edit',...
        'BackgroundColor','w',...
        'Units','normalized',...
        'Enable',enabled,...
        'Position',[pos.sec1.x2 pos.sec1.y(4) pos.sec1.w3 pos.sec1.h1],...
        'FontSize',fontsize(3),...
        'Tag',[cgstr{k} 'level'],...
        'Parent',Hcgpan(k));
    
    uicontrol('String','Im. process',...
        'Style','text',...
        'BackgroundColor',color.bg,...
        'HorizontalAlignment','left',...
        'units','normalized',...
        'Position',[pos.sec1.x1 pos.sec1.y(5) pos.sec1.w3 pos.sec1.h1],...
        'FontSize',fontsize(3),...
        'Parent',Hcgpan(k));
    uicontrol('String',improcesstype,...
        'ToolTipString','process the image',...
        'Style','popupmenu',...
        'Value',ini.([cgstr{k} 'improcess']).value,...
        'BackgroundColor','w',...
        'units','normalized',...
        'Enable',enabled,...
        'Position',[pos.sec1.x2 pos.sec1.y(5) pos.sec1.w3 pos.sec1.h1],...
        'FontSize',fontsize(3),...
        'Tag',[cgstr{k} 'improcess'],...
        'Parent',Hcgpan(k));
    
    uicontrol('String','Basis',...
        'Style','text',...
        'BackgroundColor',color.bg,...
        'HorizontalAlignment','left',...
        'units','normalized',...
        'Position',[pos.sec1.x1 pos.sec1.y(7) pos.sec1.w3 pos.sec1.h1],...
        'FontSize',fontsize(3),...
        'Parent',Hcgpan(k));
    uicontrol('String',{'basis 1';'basis 2';'basis 3';'basis 4'},...
        'ToolTipString','select the basis used for this cg step',...
        'Style','popupmenu',...
        'Value',min([4 ini.([cgstr{k} 'basis']).value]),...
        'BackgroundColor','w',...
        'units','normalized',...
        'Enable',enabled,...
        'Position',[pos.sec1.x2 pos.sec1.y(7) pos.sec1.w3 pos.sec1.h1],...
        'FontSize',fontsize(3),...
        'Tag',[cgstr{k} 'basis'],...
        'Parent',Hcgpan(k));
    
    uicontrol('String','Convcrit.',...
        'Style','text',...
        'BackgroundColor',color.bg,...
        'HorizontalAlignment','left',...
        'units','normalized',...
        'Position',[pos.sec1.x1 pos.sec1.y(8) pos.sec1.w3 pos.sec1.h1],...
        'FontSize',fontsize(3),...
        'Parent',Hcgpan(k));
    uicontrol('String',ini.([cgstr{k} 'convcrit']).value,...
        'ToolTipString','convergation criteria',...
        'Style','edit',...
        'BackgroundColor','w',...
        'units','normalized',...
        'Enable',enabled,...
        'Position',[pos.sec1.x2 pos.sec1.y(8) pos.sec1.w3 pos.sec1.h1],...
        'FontSize',fontsize(3),...
        'Tag',[cgstr{k} 'convcrit'],...
        'Parent',Hcgpan(k));
    
    uicontrol('String','Maxit.',...
        'Style','text',...
        'BackgroundColor',color.bg,...
        'HorizontalAlignment','left',...
        'units','normalized',...
        'Position',[pos.sec1.x1 pos.sec1.y(9) pos.sec1.w3 pos.sec1.h1],...
        'FontSize',fontsize(3),...
        'Parent',Hcgpan(k));
    uicontrol('String',ini.([cgstr{k} 'maxit']).value,...
        'ToolTipString','maximum number of iteration (per cg step)',...
        'Style','edit',...
        'BackgroundColor','w',...
        'units','normalized',...
        'Enable',enabled,...
        'Position',[pos.sec1.x2 pos.sec1.y(9) pos.sec1.w3 pos.sec1.h1],...
        'FontSize',fontsize(3),...
        'Tag',[cgstr{k} 'maxit'],...
        'Parent',Hcgpan(k));
    
    uicontrol('String','Im. gradient',...
        'Style','text',...
        'BackgroundColor',color.bg,...
        'HorizontalAlignment','left',...
        'units','normalized',...
        'Position',[pos.sec1.x1 pos.sec1.y(10) pos.sec1.w3 pos.sec1.h1],...
        'FontSize',fontsize(3),...
        'Parent',Hcgpan(k));
    uicontrol('String',dicgradient,...
        'ToolTipString','image gradient to apply, gradf is faster for small deformation cases, gradfg is more robust (uses 0.5(gradf+gradg))',...
        'Style','popupmenu',...
        'Value',ini.([cgstr{k} 'gradient']).value,...
        'BackgroundColor','w',...
        'units','normalized',...
        'Enable',enabled,...
        'Position',[pos.sec1.x2 pos.sec1.y(10) pos.sec1.w3 pos.sec1.h1],...
        'FontSize',fontsize(3),...
        'Tag',[cgstr{k} 'gradient'],...
        'Parent',Hcgpan(k));

    % Tikhonov
    uicontrol('String','Tikhonov Regularization',...
        'Style','text',...
        'FontWeight','bold',...
        'BackgroundColor',color.bg,...
        'units','normalized',...
        'Position',[pos.sec1.x1 pos.sec1.y(12) pos.sec1.w4 pos.sec1.h1],...
        'FontSize',fontsize(3),...
        'Parent',Hcgpan(k));

    uicontrol('String','aplha(1)',...
        'Style','text',...
        'BackgroundColor',color.bg,...
        'HorizontalAlignment','left',...
        'units','normalized',...
        'Position',[pos.sec1.x1 pos.sec1.y(13) pos.sec1.w3 pos.sec1.h1],...
        'FontSize',fontsize(3),...
        'Parent',Hcgpan(k));
    uicontrol('String',ini.([cgstr{k} 'tikhpar1']).value,...
        'ToolTipString','Tikhonov parameter (alpha) at the first iteration (relative to the largest eigenvalue of M)',...
        'Style','edit',...
        'BackgroundColor','w',...
        'units','normalized',...
        'Enable',enabled,...
        'Position',[pos.sec1.x2 pos.sec1.y(13) pos.sec1.w3 pos.sec1.h1],...
        'FontSize',fontsize(3),...
        'Tag',[cgstr{k} 'tikhpar1'],...
        'Parent',Hcgpan(k));
    
    uicontrol('String','aplha(2)',...
        'Style','text',...
        'BackgroundColor',color.bg,...
        'HorizontalAlignment','left',...
        'units','normalized',...
        'Position',[pos.sec1.x1 pos.sec1.y(14) pos.sec1.w3 pos.sec1.h1],...
        'FontSize',fontsize(3),...
        'Parent',Hcgpan(k));
    uicontrol('String',ini.([cgstr{k} 'tikhpar2']).value,...
        'ToolTipString','Tikhonov parameter (alpha) at the last Tikhonov iteration (relative to the largest eigenvalue of M)',...
        'Style','edit',...
        'BackgroundColor','w',...
        'units','normalized',...
        'Enable',enabled,...
        'Position',[pos.sec1.x2 pos.sec1.y(14) pos.sec1.w3 pos.sec1.h1],...
        'FontSize',fontsize(3),...
        'Tag',[cgstr{k} 'tikhpar2'],...
        'Parent',Hcgpan(k));
    
    uicontrol('String','steps',...
        'Style','text',...
        'BackgroundColor',color.bg,...
        'HorizontalAlignment','left',...
        'units','normalized',...
        'Position',[pos.sec1.x1 pos.sec1.y(15) pos.sec1.w3 pos.sec1.h1],...
        'FontSize',fontsize(3),...
        'Parent',Hcgpan(k));
    uicontrol('String',ini.([cgstr{k} 'tikhsteps']).value,...
        'ToolTipString','Change the Tikhonov parameter from alpha(1) to alpha(2) in N steps, set 0 to disable Tikhonov regularizatoin',...
        'Style','edit',...
        'BackgroundColor','w',...
        'units','normalized',...
        'Enable',enabled,...
        'Position',[pos.sec1.x2 pos.sec1.y(15) pos.sec1.w3 pos.sec1.h1],...
        'FontSize',fontsize(3),...
        'Tag',[cgstr{k} 'tikhsteps'],...
        'Parent',Hcgpan(k));

    
    
end
% ========================================================================


% ========================================================================
% Section 7: Correlate
% ========================================================================
axes('Parent',Hpan3(7),...
    'Position',[pos.fig.x1 pos.fig.y2 pos.fig.w4 pos.fig.h2],...
    'Box','On',...
    'NextPlot','Add',...
    'Tag','axes7',...
    'FontSize',fontsize(2));

uicontrol('String','0',...
    'ToolTipString','image id',...
    'Style','edit',...
    'BackgroundColor','w',...
    'units','normalized',...
    'Position',[pos.fig.x1 pos.fig.y1 pos.fig.w1 pos.fig.h1],...
    'FontSize',fontsize(3),...
    'HorizontalAlignment','center',...
    'Tag','corid',...
    'call',{@corid,H},...
    'Parent',Hpan3(7));

uicontrol('Style','slider',...
    'BackgroundColor',color.bg,...
    'units','normalized',...
    'Position',[pos.fig.x2 pos.fig.y1 pos.fig.w2 pos.fig.h1],...
    'Tag','corslider',...
    'Min',0,...
    'Max',1,...
    'Sliderstep',[0.01 0.1],...
    'Value',1,...
    'call',{@corslider,H},...
    'Parent',Hpan3(7));

% Go, Continue, Stop
uicontrol('String','Go',...
    'ToolTipString','start the correlation process',...
    'Style','togglebutton',...
    'Value',0,...
    'BackgroundColor',color.bg,...
    'units','normalized',...
    'Position',[pos.sec1.xb(1) pos.sec1.y(1) pos.sec1.wb pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Tag','corgo',...
    'Parent',Hpan2(7),...
    'call',{@corgo,H});
uicontrol('String','Continue',...
    'ToolTipString','force convergence on the current cg step, continue to the next',...
    'Style','togglebutton',...
    'Value',0,...
    'BackgroundColor',color.bg,...
    'units','normalized',...
    'Position',[pos.sec1.xb(2) pos.sec1.y(1) pos.sec1.wb pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Tag','corcontinue',...
    'Parent',Hpan2(7));
uicontrol('String','Stop',...
    'ToolTipString','stop the correlation process (please wait for the command to be processed)',...
    'Style','togglebutton',...
    'Value',1,...
    'BackgroundColor',color.hl,...
    'units','normalized',...
    'Position',[pos.sec1.xb(3) pos.sec1.y(1) pos.sec1.wb pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Tag','corstop',...
    'Parent',Hpan2(7),...
    'call',{@corstop,H});

% Clear one, all
uicontrol('String','Clear One',...
    'ToolTipString','clear the correlation results of the current increment',...
    'Style','pushbutton',...
    'BackgroundColor',color.bg,...
    'units','normalized',...
    'Position',[pos.sec1.xb(1) pos.sec1.y(2) pos.sec1.wb pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Tag','corclearinc',...
    'Parent',Hpan2(7),...
    'call',{@corclearinc,H});
uicontrol('String','Clear All',...
    'ToolTipString','clear correlation results, start fresh',...
    'Style','pushbutton',...
    'BackgroundColor',color.bg,...
    'units','normalized',...
    'Position',[pos.sec1.xb(1) pos.sec1.y(3) pos.sec1.wb pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Tag','corclear',...
    'Parent',Hpan2(7),...
    'call',{@corclear,H});

% Reuse one, all
uicontrol('String','Restart One',...
    'ToolTipString','restart the correlation of this increment (when pressing "go")',...
    'Style','pushbutton',...
    'BackgroundColor',color.bg,...
    'units','normalized',...
    'Position',[pos.sec1.xb(2) pos.sec1.y(2) pos.sec1.wb pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Tag','correstartinc',...
    'Parent',Hpan2(7),...
    'call',{@correstartinc,H});
uicontrol('String','Restart All',...
    'ToolTipString','restart the correlation of all increment (when pressing "go")',...
    'Style','pushbutton',...
    'BackgroundColor',color.bg,...
    'units','normalized',...
    'Position',[pos.sec1.xb(2) pos.sec1.y(3) pos.sec1.wb pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Tag','correstart',...
    'Parent',Hpan2(7),...
    'call',{@correstart,H});

uicontrol('String','to iguess',...
    'ToolTipString','save results as initial guess',...
    'Style','pushbutton',...
    'BackgroundColor',color.bg,...
    'units','normalized',...
    'Position',[pos.sec1.xb(3) pos.sec1.y(2) pos.sec1.wb pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Tag','cor2iguess',...
    'Parent',Hpan2(7),...
    'call',{@cor2iguess,H});
uicontrol('String',{'0';'1';'2'},...
    'ToolTipString','how often to update the live view (0 = never, 1 = once per cg step, 2 = each iteration)',...
    'Value',ini.corliveview.value,...
    'Style','popupmenu',...
    'BackgroundColor','w',...
    'units','normalized',...
    'Position',[pos.sec1.xb(3) pos.sec1.y(3) pos.sec1.wb pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Tag','corliveview',...
    'Parent',Hpan2(7));

h = pos.sec1.y(3) - (pos.sec1.y(end) + 0.02);
uicontrol('Style','edit',...
    'Max',2,...
    'String',{''},...
    'Enable','inactive',...
    'units','normalized',...
    'BackgroundColor','w',...
    'Position',[pos.sec1.x1 pos.sec1.y(end) pos.sec1.w4 h],...
    'FontSize',fontsize(1),...
    'FontName',fixwidthfont,...
    'HorizontalAlignment','left',...
    'Tag','corstatus',...
    'Parent',Hpan2(7));

% ========================================================================
% Section 8: Results
% ========================================================================
axes('Parent',Hpan3(8),...
    'Position',[pos.fig.x1 pos.fig.y2 pos.fig.w4-0.02 pos.fig.h2],...
    'Box','On',...
    'NextPlot','Add',...
    'Tag','axes8',...
    'FontSize',fontsize(2));

uicontrol('String','0',...
    'ToolTipString','lower color limit',...
    'Style','edit',...
    'BackgroundColor','w',...
    'units','normalized',...
    'Position',[0.94 pos.fig.y2 0.05 pos.fig.h1],...
    'FontSize',fontsize(3),...
    'HorizontalAlignment','center',...
    'Tag','resclim1',...
    'call',{@plotres,H},...
    'Parent',Hpan3(8));

uicontrol('String','0',...
    'ToolTipString','upper color limit',...
    'Style','edit',...
    'BackgroundColor','w',...
    'units','normalized',...
    'Position',[0.94 pos.fig.y2+pos.fig.h2-pos.fig.h1 0.05 pos.fig.h1],...
    'FontSize',fontsize(3),...
    'HorizontalAlignment','center',...
    'Tag','resclim2',...
    'call',{@plotres,H},...
    'Parent',Hpan3(8));

uicontrol('String','1',...
    'ToolTipString','image id',...
    'Style','edit',...
    'BackgroundColor','w',...
    'units','normalized',...
    'Position',[pos.fig.x1 pos.fig.y1 pos.fig.w1 pos.fig.h1],...
    'FontSize',fontsize(3),...
    'HorizontalAlignment','center',...
    'Tag','resid',...
    'call',{@resid,H},...
    'Parent',Hpan3(8));

uicontrol('Style','slider',...
    'BackgroundColor',color.bg,...
    'units','normalized',...
    'Position',[pos.fig.x2 pos.fig.y1 pos.fig.w2 pos.fig.h1],...
    'Tag','resslider',...
    'Min',0,...
    'Max',1,...
    'Sliderstep',[0.01 0.1],...
    'Value',1,...
    'call',{@resslider,H},...
    'Parent',Hpan3(8));

% Pattern controls
uicontrol('String','Pattern',...
    'Style','text',...
    'FontWeight','bold',...
    'BackgroundColor',color.bg,...
    'units','normalized',...
    'Position',[pos.sec1.x1 pos.sec1.y(1) pos.sec1.w4 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Parent',Hpan2(8));

underlay{1,1} = 'f';
underlay{2,1} = 'g';
underlay{3,1} = 'gtilde';
underlay{4,1} = 'r';
underlay{5,1} = 'none';
uicontrol('String',underlay,...
    'ToolTipString','what pattern to show',...
    'Style','popupmenu',...
    'Value',ini.resunderlay.value,...
    'BackgroundColor','w',...
    'units','normalized',...
    'Position',[pos.sec1.x1 pos.sec1.y(2) pos.sec1.w4 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Tag','resunderlay',...
    'call',{@plotres,H},...
    'Parent',Hpan2(8));

uicontrol('String',ini.ressoftening.value,...
    'Style','edit',...
    'Enable','inactive',...
    'BackgroundColor',color.bg,...
    'HorizontalAlignment','center',...
    'units','normalized',...
    'Position',[pos.sec1.x1 pos.sec1.y(3) pos.sec1.w5 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Tag','ressoftening',...
    'Parent',Hpan2(8));
uicontrol('Style','slider',...
    'ToolTipString','soften the pattern',...
    'BackgroundColor',color.bg,...
    'units','normalized',...
    'Position',[pos.sec1.x3 pos.sec1.y(3) pos.sec1.w6 pos.sec1.h1],...
    'Tag','ressofteningslider',...
    'Min',0,...
    'Max',1,...
    'Sliderstep',[0.01 0.1],...
    'Value',str2double(ini.ressoftening.value),...
    'call',{@plotres,H},...
    'Parent',Hpan2(8));

% Overlay controls
uicontrol('String','Overlay',...
    'Style','text',...
    'FontWeight','bold',...
    'BackgroundColor',color.bg,...
    'units','normalized',...
    'Position',[pos.sec1.x1 pos.sec1.y(5) pos.sec1.w4 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Parent',Hpan2(8));

overlay{ 1,1} = 'U1 (x)';
overlay{ 2,1} = 'U2 (y)';
overlay{ 3,1} = 'U3 (z or Constant)';
overlay{ 4,1} = 'U4 (Linear)';
overlay{ 5,1} = 'U5 (Quadratic)';
overlay{ 6,1} = 'U6 (Cubic)';
overlay{ 7,1} = 'strain xx';
overlay{ 8,1} = 'strain yy';
overlay{ 9,1} = 'strain xy';
overlay{10,1} = 'strain yx';
overlay{11,1} = 'strain maj';
overlay{12,1} = 'strain min';
overlay{13,1} = 'strain eq.';
overlay{14,1} = 'r';
overlay{15,1} = 'q';
overlay{16,1} = 'none';
uicontrol('String',overlay,...
    'ToolTipString','what overlay to show',...
    'Style','popupmenu',...
    'Value',ini.resoverlay.value,...
    'BackgroundColor','w',...
    'units','normalized',...
    'Position',[pos.sec1.x1 pos.sec1.y(6) pos.sec1.w4 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Tag','resoverlay',...
    'call',{@plotres,H},...
    'Parent',Hpan2(8));

uicontrol('String',ini.resalpha.value,...
    'Style','edit',...
    'Enable','inactive',...
    'BackgroundColor',color.bg,...
    'HorizontalAlignment','center',...
    'units','normalized',...
    'Position',[pos.sec1.x1 pos.sec1.y(7) pos.sec1.w5 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Tag','resalpha',...
    'Parent',Hpan2(8));
uicontrol('Style','slider',...
    'ToolTipString','overlay transparency',...
    'BackgroundColor',color.bg,...
    'units','normalized',...
    'Position',[pos.sec1.x3 pos.sec1.y(7) pos.sec1.w6 pos.sec1.h1],...
    'Tag','resalphaslider',...
    'Min',0,...
    'Max',1,...
    'Sliderstep',[0.01 0.1],...
    'Value',str2double(ini.resalpha.value),...
    'call',{@plotres,H},...
    'Parent',Hpan2(8));

% Arrow controls
uicontrol('String','Vectors',...
    'Style','text',...
    'FontWeight','bold',...
    'BackgroundColor',color.bg,...
    'units','normalized',...
    'Position',[pos.sec1.x1 pos.sec1.y(9) pos.sec1.w4 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Parent',Hpan2(8));

arrows{ 1,1} = 'U (x,y)';
arrows{ 2,1} = 'strain (xx,yy)';
arrows{ 3,1} = 'strain (min,maj)';
arrows{ 4,1} = 'none';
uicontrol('String',arrows,...
    'ToolTipString','what overlay to show',...
    'Style','popupmenu',...
    'Value',ini.resarrows.value,...
    'BackgroundColor','w',...
    'units','normalized',...
    'Position',[pos.sec1.x1 pos.sec1.y(10) pos.sec1.w4 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Tag','resarrows',...
    'call',{@plotres,H},...
    'Parent',Hpan2(8));

uicontrol('String',ini.resarrowscale.value,...
    'Style','edit',...
    'Enable','inactive',...
    'BackgroundColor',color.bg,...
    'HorizontalAlignment','center',...
    'units','normalized',...
    'Position',[pos.sec1.x1 pos.sec1.y(11) pos.sec1.w5 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Tag','resarrowscale',...
    'Parent',Hpan2(8));
uicontrol('Style','slider',...
    'ToolTipString','arrow scale factor',...
    'BackgroundColor',color.bg,...
    'units','normalized',...
    'Position',[pos.sec1.x3 pos.sec1.y(11) pos.sec1.w6 pos.sec1.h1],...
    'Tag','resarrowscaleslider',...
    'Min',0,...
    'Max',100,...
    'Sliderstep',[0.001 0.01],...
    'Value',str2double(ini.resarrowscale.value),...
    'call',{@plotres,H},...
    'Parent',Hpan2(8));

% extra result options
uicontrol('String','Pixelsize',...
    'Style','text',...
    'BackgroundColor',color.bg,...
    'HorizontalAlignment','left',...
    'units','normalized',...
    'Position',[pos.sec1.xb(1) pos.sec1.y(end-3) pos.sec1.wb pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Parent',Hpan2(8));
uicontrol('String',ini.respixelsize.value,...
    'ToolTipString','size of a pixel in the unit selected below',...
    'Style','edit',...
    'BackgroundColor','w',...
    'units','normalized',...
    'Position',[pos.sec1.xb(2) pos.sec1.y(end-3) pos.sec1.wb pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Tag','respixelsize',...
    'call',{@plotres,H},...
    'Parent',Hpan2(8));

units{ 1,1} = 'nm';
units{ 2,1} = 'um';
units{ 3,1} = 'mm';
units{ 4,1} = 'm';
units{ 4,1} = 'km';
units{ 5,1} = 'px';
units{ 6,1} = 'inch';
units{ 7,1} = 'ft.';
uicontrol('String',units,...
    'ToolTipString','unit of the pixelsize',...
    'Style','popupmenu',...
    'Value',ini.resunit.value,...
    'BackgroundColor','w',...
    'units','normalized',...
    'Position',[pos.sec1.xb(3) pos.sec1.y(end-3) pos.sec1.wb pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Tag','resunit',...
    'call',{@plotres,H},...
    'Parent',Hpan2(8));

straindef{ 1,1} = 'small strain'; 
straindef{ 2,1} = 'logarithmic strain'; 
straindef{ 3,1} = 'Green-Lagrange strain';
straindef{ 4,1} = 'Euler-Almansi strain';
straindef{ 5,1} = 'membrane strain';
straindef{ 6,1} = 'none';
uicontrol('String',straindef,...
    'ToolTipString','strain definition',...
    'Style','popupmenu',...
    'Value',ini.resstraindef.value,...
    'BackgroundColor','w',...
    'units','normalized',...
    'Position',[pos.sec1.x1 pos.sec1.y(end-2) pos.sec1.w4 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Tag','resstraindef',...
    'call',{@plotres,H,1},...
    'Parent',Hpan2(8));

renderer{1,1} = 'OpenGL';
renderer{2,1} = 'zbuffer';
renderer{3,1} = 'painters';
uicontrol('String','renderer',...
    'Style','text',...
    'BackgroundColor',color.bg,...
    'HorizontalAlignment','left',...
    'units','normalized',...
    'Position',[pos.sec1.x1 pos.sec1.y(end-1) pos.sec1.w3 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Parent',Hpan2(8));
uicontrol('String',renderer,...
    'ToolTipString','switch to a different renderer (switch this when some parts of the plot are not proberly rendered)',...
    'Style','popupmenu',...
    'Value',ini.resrenderer.value,...
    'BackgroundColor','w',...
    'units','normalized',...
    'Position',[pos.sec1.x2 pos.sec1.y(end-1) pos.sec1.w3 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Tag','resrenderer',...
    'call',{@resrenderer,H},...
    'Parent',Hpan2(8));


uicontrol('String','Save',...
    'ToolTipString','save result figure',...
    'Style','pushbutton',...
    'BackgroundColor',color.bg,...
    'units','normalized',...
    'Position',[pos.sec1.x1 pos.sec1.y(end) pos.sec1.w3 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Tag','ressave',...
    'Parent',Hpan2(8),...
    'call',{@ressave,H});

% crosssection
uicontrol('String','Cross-section',...
    'ToolTipString','open cross-section controls',...
    'Style','pushbutton',...
    'Enable','inactive',...
    'BackgroundColor',color.bg,...
    'ForegroundColor',0.5*color.bg,...
    'units','normalized',...
    'Position',[pos.sec1.x2 pos.sec1.y(end) pos.sec1.w3 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Tag','rescrosssection',...
    'call',{@rescrosssection,H},...
    'Parent',Hpan2(8));


% ========================================================================
% Section 9: Info
% ========================================================================

ipanlabel{1,1} = 'Info';
ipanlabel{2,1} = 'Status';
ipanlabel{3,1} = 'Help';

pos.ipan = [0 0 1 1];
for k = 1:3
    if k == 3
        visible = 'on';
    else
        visible = 'off';
    end
    Hipan(k) = uipanel('Title',ipanlabel{k},'FontSize',fontsize(2),...
        'BackgroundColor',color.bg,...
        'TitlePosition','lefttop',...
        'Visible',visible,...
        'units','normalized',...
        'Tag',['infopan' num2str(k)],...
        'Parent',Hpan3(9),...
        'Position',pos.ipan);
end

uicontrol('String','Info',...
    'ToolTipString','Show info panel',...
    'Style','pushbutton',...
    'BackgroundColor',color.bg,...
    'units','normalized',...
    'Position',[pos.sec1.x1 pos.sec1.y(1) pos.sec1.w4 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Tag','infobut1',...
    'Parent',Hpan2(9),...
    'call',{@infobutton,H,1});

uicontrol('String','Status',...
    'ToolTipString','Show status panel',...
    'Style','pushbutton',...
    'BackgroundColor',color.bg,...
    'units','normalized',...
    'HorizontalAlignment','left',...
    'Position',[pos.sec1.x1 pos.sec1.y(2) pos.sec1.w4 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Tag','infobut2',...
    'Parent',Hpan2(9),...
    'call',{@infobutton,H,2});

uicontrol('String','Help',...
    'ToolTipString','Show help panel',...
    'Style','pushbutton',...
    'BackgroundColor',color.hl,...
    'units','normalized',...
    'Position',[pos.sec1.x1 pos.sec1.y(3) pos.sec1.w4 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Tag','infobut3',...
    'Parent',Hpan2(9),...
    'call',{@infobutton,H,3});


uicontrol('String','Save guidata to D',...
    'ToolTipString','save the guidata to the D structure in the base workspace',...
    'Style','pushbutton',...
    'BackgroundColor',color.bg,...
    'units','normalized',...
    'Position',[pos.sec1.x1 pos.sec1.y(end-4) pos.sec1.w4 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Parent',Hpan2(9),...
    'call',{@infoguidataput,H});

uicontrol('String','Load guidata from D',...
    'ToolTipString','load the D structure from the base workspace to the guidata',...
    'Style','pushbutton',...
    'BackgroundColor',color.bg,...
    'units','normalized',...
    'Position',[pos.sec1.x1 pos.sec1.y(end-3) pos.sec1.w4 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Parent',Hpan2(9),...
    'call',{@infoguidataget,H});


uicontrol('String','Reset GUI',...
    'ToolTipString','reset the GUI state',...
    'Style','pushbutton',...
    'BackgroundColor',color.bg,...
    'units','normalized',...
    'Position',[pos.sec1.x1 pos.sec1.y(end-1) pos.sec1.w4 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Tag','inforeset',...
    'Parent',Hpan2(9),...
    'call',{@inforeset,H});

uicontrol('String','Save',...
    'ToolTipString','save GUI state to file',...
    'Style','pushbutton',...
    'BackgroundColor',color.bg,...
    'units','normalized',...
    'Position',[pos.sec1.x1 pos.sec1.y(end) pos.sec1.w3 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Tag','infosave',...
    'Parent',Hpan2(9),...
    'call',{@infosave,H});

uicontrol('String','Load',...
    'ToolTipString','load GUI state from file',...
    'Style','pushbutton',...
    'BackgroundColor',color.bg,...
    'units','normalized',...
    'Position',[pos.sec1.x2 pos.sec1.y(end) pos.sec1.w3 pos.sec1.h1],...
    'FontSize',fontsize(3),...
    'Tag','infoload',...
    'Parent',Hpan2(9),...
    'call',{@infoload,H});

% Info - Info
% ============================

x = [0.02 0.4];
y = 0.05;
w = [0.37 0.58];
h = 0.92;
h2 = 0.03;

pos.itable(1,:) = [x(1) y w(1) h];
pos.itable(2,:) = [x(2) y w(2) h];

pos.itxt(1,:) = [x(1) y+h w(1) h2];
pos.itxt(2,:) = [x(2) y+h w(2) h2];

str{1,1} = 'General Info';
str{2,1} = 'Correlation Info';

% general info
uicontrol('String',str{1},...
    'Style','text',...
    'BackgroundColor',color.bg,...
    'HorizontalAlignment','center',...
    'units','normalized',...
    'Position',pos.itxt(1,:),...
    'FontSize',fontsize(3),...
    'FontWeight','bold',...
    'Parent',Hipan(1));
uitable('units','normalized',...
    'Position',pos.itable(1,:),...
    'FontSize',fontsize(1),...
    'Enable','On',...
    'Tag','infogeneral',...
    'Parent',Hipan(1));

% correlation info
uicontrol('String',str{2},...
    'Style','text',...
    'BackgroundColor',color.bg,...
    'HorizontalAlignment','center',...
    'units','normalized',...
    'Position',pos.itxt(2,:),...
    'FontSize',fontsize(3),...
    'FontWeight','bold',...
    'Parent',Hipan(1));
uitable('units','normalized',...
    'Position',pos.itable(2,:),...
    'FontSize',fontsize(1),...
    'Enable','On',...
    'Tag','infocorrelation',...
    'Parent',Hipan(1));

% Info - Status
% ============================

uicontrol('Style','edit',...
    'Max',2,...
    'String','Status',...
    'Enable','inactive',...
    'units','normalized',...
    'BackgroundColor','w',...
    'HorizontalAlignment','left',...
    'Position',pos.ipan,...
    'FontSize',fontsize(3),...
    'FontName',fixwidthfont,...
    'Tag','status',...
    'Parent',Hipan(2));


% Info - Help
% ============================

Hhelp = uicontrol('Style','edit',...
    'Max',2,...
    'String','Help',...
    'Enable','inactive',...
    'units','normalized',...
    'BackgroundColor','w',...
    'HorizontalAlignment','left',...
    'Position',pos.ipan,...
    'FontSize',fontsize(3),...
    'FontName',fixwidthfont,...
    'Tag','help',...
    'Parent',Hipan(3));
